backend:
  name: github
  repo: yourusername/https://github.com/E40sr/portfolio.git
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Main Content", name: "body", widget: "markdown"}
